//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation of deletion.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        public static string MainViewDashboardsMenu {
            get {
                return ResourceManager.GetString("MainViewDashboardsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string MainViewDirectoriesMenu {
            get {
                return ResourceManager.GetString("MainViewDirectoriesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainViewHelpMenu {
            get {
                return ResourceManager.GetString("MainViewHelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string MainViewMaterialsMenu {
            get {
                return ResourceManager.GetString("MainViewMaterialsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Formats.
        /// </summary>
        public static string MainViewPrintFormatsMenu {
            get {
                return ResourceManager.GetString("MainViewPrintFormatsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MainViewProfileMenu {
            get {
                return ResourceManager.GetString("MainViewProfileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        public static string MainViewReportingMenu {
            get {
                return ResourceManager.GetString("MainViewReportingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MainViewSearchMenu {
            get {
                return ResourceManager.GetString("MainViewSearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string MainViewSuppliersMenu {
            get {
                return ResourceManager.GetString("MainViewSuppliersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        public static string MainViewWarehousesMenu {
            get {
                return ResourceManager.GetString("MainViewWarehousesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add.
        /// </summary>
        public static string PlusAdd {
            get {
                return ResourceManager.GetString("PlusAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SupplierFormAddressLabel {
            get {
                return ResourceManager.GetString("SupplierFormAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string SupplierFormContactPersonLabel {
            get {
                return ResourceManager.GetString("SupplierFormContactPersonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SupplierFormEmailLabel {
            get {
                return ResourceManager.GetString("SupplierFormEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SupplierFormNameLabel {
            get {
                return ResourceManager.GetString("SupplierFormNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string SupplierFormPhoneNumberLabel {
            get {
                return ResourceManager.GetString("SupplierFormPhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string SupplierFormSupplierTitle {
            get {
                return ResourceManager.GetString("SupplierFormSupplierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filter.
        /// </summary>
        public static string SuppliersControlApplyFilter {
            get {
                return ResourceManager.GetString("SuppliersControlApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string SuppliersControlClearFilter {
            get {
                return ResourceManager.GetString("SuppliersControlClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting:.
        /// </summary>
        public static string SuppliersControlDeleteError {
            get {
                return ResourceManager.GetString("SuppliersControlDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete supplier {0}?.
        /// </summary>
        public static string SuppliersControlDeleteSupplierConfirmation {
            get {
                return ResourceManager.GetString("SuppliersControlDeleteSupplierConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load suppliers:.
        /// </summary>
        public static string SuppliersControlLoadSuppliersError {
            get {
                return ResourceManager.GetString("SuppliersControlLoadSuppliersError", resourceCulture);
            }
        }
    }
}
